services:
  backend-service:
    build: ./back-end
    ports:
      - "8080:8080"
    depends_on:
      redis-service:
        condition: service_started
    env_file:
      - ./back-end/.env
    environment:
      - REDIS_URL=redis://redis-service:6379
      - FRONTEND_URL=http://frontend-service:3000
    restart: unless-stopped

  frontend-service:
    build: 
      context: ./front-end
      # ส่งค่าเข้าไปให้ Next.js เห็น "ตอนกำลัง Build"
      args:
        # สมมติว่าคุณต้องการเทสต์ในเครื่อง ให้ Browser ยิงไปที่ localhost
        - NEXT_PUBLIC_BACKEND_HTTP=http://backend-service:8080/api/v1
        - NEXT_PUBLIC_BACKEND_WEBSOCKET=ws://backend-service:8080/ws
    ports:
      - "3000:3000"
    depends_on:
      - backend-service
    env_file:
      - ./front-end/.env.local
    restart: unless-stopped

  redis-service:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped