# version: '3.8'

services:
  # backend-service:
  #   build: ./back-end
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - redis-service
  #   env_file:
  #     - ./back-end/.env  # ระบุ Path ไปที่ไฟล์ .env ของคุณ
  #   environment:
  #     - REDIS_ADDR=redis-service:6379

  redis-service:
    image: redis:7-alpine
    ports:
      - "6379:6379" # เปิด port เผื่ออยากใช้ Redis Insight เข้าไปดู
    command: redis-server --save 60 1 --loglevel warning