// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ApisitKhakmueang/BookingConferenceRoom/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// BookingPostgresRepo is an autogenerated mock type for the BookingPostgresRepo type
type BookingPostgresRepo struct {
	mock.Mock
}

// CheckDayOff provides a mock function with given fields: ctx, date
func (_m *BookingPostgresRepo) CheckDayOff(ctx context.Context, date time.Time) error {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for CheckDayOff")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = rf(ctx, date)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckInBooking provides a mock function with given fields: ctx, roomID, passcode
func (_m *BookingPostgresRepo) CheckInBooking(ctx context.Context, roomID uuid.UUID, passcode string) error {
	ret := _m.Called(ctx, roomID, passcode)

	if len(ret) == 0 {
		panic("no return value specified for CheckInBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, roomID, passcode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckOutBookingDB provides a mock function with given fields: ctx, booking
func (_m *BookingPostgresRepo) CheckOutBookingDB(ctx context.Context, booking *domain.Booking) (*domain.Booking, error) {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for CheckOutBookingDB")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking) (*domain.Booking, error)); ok {
		return rf(ctx, booking)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking) *domain.Booking); ok {
		r0 = rf(ctx, booking)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Booking) error); ok {
		r1 = rf(ctx, booking)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateBookingDB provides a mock function with given fields: ctx, booking
func (_m *BookingPostgresRepo) CreateBookingDB(ctx context.Context, booking *domain.Booking) (*domain.Booking, error) {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for CreateBookingDB")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking) (*domain.Booking, error)); ok {
		return rf(ctx, booking)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking) *domain.Booking); ok {
		r0 = rf(ctx, booking)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Booking) error); ok {
		r1 = rf(ctx, booking)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBookingDB provides a mock function with given fields: ctx, booking
func (_m *BookingPostgresRepo) DeleteBookingDB(ctx context.Context, booking *domain.Booking) (*domain.Booking, error) {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBookingDB")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking) (*domain.Booking, error)); ok {
		return rf(ctx, booking)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking) *domain.Booking); ok {
		r0 = rf(ctx, booking)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Booking) error); ok {
		r1 = rf(ctx, booking)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAnalyticBookingDB provides a mock function with given fields: ctx, date
func (_m *BookingPostgresRepo) GetAnalyticBookingDB(ctx context.Context, date *domain.Date) ([]domain.Booking, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetAnalyticBookingDB")
	}

	var r0 []domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date) ([]domain.Booking, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date) []domain.Booking); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Date) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookingByDayDB provides a mock function with given fields: ctx, date
func (_m *BookingPostgresRepo) GetBookingByDayDB(ctx context.Context, date *domain.Date) ([]domain.Booking, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingByDayDB")
	}

	var r0 []domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date) ([]domain.Booking, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date) []domain.Booking); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Date) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookingByID provides a mock function with given fields: ctx, id
func (_m *BookingPostgresRepo) GetBookingByID(ctx context.Context, id uuid.UUID) (*domain.Booking, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingByID")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Booking, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Booking); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookingDB provides a mock function with given fields: ctx, dateTime, roomID
func (_m *BookingPostgresRepo) GetBookingDB(ctx context.Context, dateTime *domain.Date, roomID uuid.UUID) ([]domain.Booking, error) {
	ret := _m.Called(ctx, dateTime, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingDB")
	}

	var r0 []domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date, uuid.UUID) ([]domain.Booking, error)); ok {
		return rf(ctx, dateTime, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date, uuid.UUID) []domain.Booking); ok {
		r0 = rf(ctx, dateTime, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Date, uuid.UUID) error); ok {
		r1 = rf(ctx, dateTime, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookingStatusByRoomID_DB provides a mock function with given fields: ctx, roomID
func (_m *BookingPostgresRepo) GetBookingStatusByRoomID_DB(ctx context.Context, roomID uuid.UUID) (*domain.Booking, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingStatusByRoomID_DB")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Booking, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Booking); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookingStatusDB provides a mock function with given fields: ctx
func (_m *BookingPostgresRepo) GetBookingStatusDB(ctx context.Context) ([]domain.Booking, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingStatusDB")
	}

	var r0 []domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Booking, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Booking); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConfigDB provides a mock function with given fields: ctx
func (_m *BookingPostgresRepo) GetConfigDB(ctx context.Context) (*domain.Config, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigDB")
	}

	var r0 *domain.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.Config, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.Config); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoomID provides a mock function with given fields: ctx, booking, roomNumber
func (_m *BookingPostgresRepo) GetRoomID(ctx context.Context, booking *domain.Booking, roomNumber uint) error {
	ret := _m.Called(ctx, booking, roomNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking, uint) error); ok {
		r0 = rf(ctx, booking, roomNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRoomNumberDB provides a mock function with given fields: ctx, bookingID
func (_m *BookingPostgresRepo) GetRoomNumberDB(ctx context.Context, bookingID uuid.UUID) (uint, error) {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomNumberDB")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uint, error)); ok {
		return rf(ctx, bookingID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) uint); ok {
		r0 = rf(ctx, bookingID)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUpNextBookingDB provides a mock function with given fields: ctx, endOfDay
func (_m *BookingPostgresRepo) GetUpNextBookingDB(ctx context.Context, endOfDay time.Time) (*domain.Booking, error) {
	ret := _m.Called(ctx, endOfDay)

	if len(ret) == 0 {
		panic("no return value specified for GetUpNextBookingDB")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (*domain.Booking, error)); ok {
		return rf(ctx, endOfDay)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) *domain.Booking); ok {
		r0 = rf(ctx, endOfDay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, endOfDay)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserBookingDB provides a mock function with given fields: ctx, userID, date
func (_m *BookingPostgresRepo) GetUserBookingDB(ctx context.Context, userID uuid.UUID, date string) ([]domain.Booking, error) {
	ret := _m.Called(ctx, userID, date)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBookingDB")
	}

	var r0 []domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]domain.Booking, error)); ok {
		return rf(ctx, userID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []domain.Booking); ok {
		r0 = rf(ctx, userID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserHistoryDB provides a mock function with given fields: ctx, userID, date
func (_m *BookingPostgresRepo) GetUserHistoryDB(ctx context.Context, userID uuid.UUID, date string) ([]domain.Booking, error) {
	ret := _m.Called(ctx, userID, date)

	if len(ret) == 0 {
		panic("no return value specified for GetUserHistoryDB")
	}

	var r0 []domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]domain.Booking, error)); ok {
		return rf(ctx, userID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []domain.Booking); ok {
		r0 = rf(ctx, userID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsPasscodeAvailable provides a mock function with given fields: ctx, booking, passcode
func (_m *BookingPostgresRepo) IsPasscodeAvailable(ctx context.Context, booking *domain.Booking, passcode string) bool {
	ret := _m.Called(ctx, booking, passcode)

	if len(ret) == 0 {
		panic("no return value specified for IsPasscodeAvailable")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking, string) bool); ok {
		r0 = rf(ctx, booking, passcode)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsRoomAvailable provides a mock function with given fields: ctx, booking
func (_m *BookingPostgresRepo) IsRoomAvailable(ctx context.Context, booking *domain.Booking) bool {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for IsRoomAvailable")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking) bool); ok {
		r0 = rf(ctx, booking)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// UpdateBookingDB provides a mock function with given fields: ctx, booking
func (_m *BookingPostgresRepo) UpdateBookingDB(ctx context.Context, booking *domain.Booking) (*domain.Booking, error) {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookingDB")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking) (*domain.Booking, error)); ok {
		return rf(ctx, booking)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking) *domain.Booking); ok {
		r0 = rf(ctx, booking)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Booking) error); ok {
		r1 = rf(ctx, booking)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBookingStatusDB provides a mock function with given fields: ctx, bookingID, status
func (_m *BookingPostgresRepo) UpdateBookingStatusDB(ctx context.Context, bookingID uuid.UUID, status string) (*domain.Booking, error) {
	ret := _m.Called(ctx, bookingID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookingStatusDB")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*domain.Booking, error)); ok {
		return rf(ctx, bookingID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *domain.Booking); ok {
		r0 = rf(ctx, bookingID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, bookingID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBookingPostgresRepo creates a new instance of BookingPostgresRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingPostgresRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingPostgresRepo {
	mock := &BookingPostgresRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
