// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ApisitKhakmueang/BookingConferenceRoom/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// BookingUsecases is an autogenerated mock type for the BookingUsecases type
type BookingUsecases struct {
	mock.Mock
}

// CheckInBooking provides a mock function with given fields: ctx, roomID, passcode
func (_m *BookingUsecases) CheckInBooking(ctx context.Context, roomID uuid.UUID, passcode string) error {
	ret := _m.Called(ctx, roomID, passcode)

	if len(ret) == 0 {
		panic("no return value specified for CheckInBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, roomID, passcode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckOutBooking provides a mock function with given fields: ctx, booking
func (_m *BookingUsecases) CheckOutBooking(ctx context.Context, booking *domain.Booking) error {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for CheckOutBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking) error); ok {
		r0 = rf(ctx, booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBooking provides a mock function with given fields: ctx, booking, roomNumber
func (_m *BookingUsecases) CreateBooking(ctx context.Context, booking *domain.Booking, roomNumber uint) error {
	ret := _m.Called(ctx, booking, roomNumber)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking, uint) error); ok {
		r0 = rf(ctx, booking, roomNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBooking provides a mock function with given fields: ctx, booking
func (_m *BookingUsecases) DeleteBooking(ctx context.Context, booking *domain.Booking) error {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking) error); ok {
		r0 = rf(ctx, booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAnalyticBooking provides a mock function with given fields: ctx, date
func (_m *BookingUsecases) GetAnalyticBooking(ctx context.Context, date *domain.Date) (*domain.UpNextBookingResponse, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetAnalyticBooking")
	}

	var r0 *domain.UpNextBookingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date) (*domain.UpNextBookingResponse, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date) *domain.UpNextBookingResponse); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UpNextBookingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Date) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBooking provides a mock function with given fields: ctx, date, roomNumber
func (_m *BookingUsecases) GetBooking(ctx context.Context, date *domain.Date, roomNumber uint) ([]domain.Booking, error) {
	ret := _m.Called(ctx, date, roomNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetBooking")
	}

	var r0 []domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date, uint) ([]domain.Booking, error)); ok {
		return rf(ctx, date, roomNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date, uint) []domain.Booking); ok {
		r0 = rf(ctx, date, roomNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Date, uint) error); ok {
		r1 = rf(ctx, date, roomNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookingByDay provides a mock function with given fields: ctx, DateStr
func (_m *BookingUsecases) GetBookingByDay(ctx context.Context, DateStr string) ([]domain.Booking, error) {
	ret := _m.Called(ctx, DateStr)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingByDay")
	}

	var r0 []domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Booking, error)); ok {
		return rf(ctx, DateStr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Booking); ok {
		r0 = rf(ctx, DateStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, DateStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookingStatus provides a mock function with given fields: ctx
func (_m *BookingUsecases) GetBookingStatus(ctx context.Context) ([]domain.Booking, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingStatus")
	}

	var r0 []domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Booking, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Booking); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookingStatusByRoomID provides a mock function with given fields: ctx, roomID
func (_m *BookingUsecases) GetBookingStatusByRoomID(ctx context.Context, roomID uuid.UUID) (*domain.Booking, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingStatusByRoomID")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Booking, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Booking); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUpNextBooking provides a mock function with given fields: ctx, date
func (_m *BookingUsecases) GetUpNextBooking(ctx context.Context, date string) (*domain.Booking, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetUpNextBooking")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Booking, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Booking); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserBooking provides a mock function with given fields: ctx, userID, date
func (_m *BookingUsecases) GetUserBooking(ctx context.Context, userID uuid.UUID, date string) ([]domain.Booking, error) {
	ret := _m.Called(ctx, userID, date)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBooking")
	}

	var r0 []domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]domain.Booking, error)); ok {
		return rf(ctx, userID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []domain.Booking); ok {
		r0 = rf(ctx, userID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserHistory provides a mock function with given fields: ctx, userID, date
func (_m *BookingUsecases) GetUserHistory(ctx context.Context, userID uuid.UUID, date string) ([]domain.Booking, error) {
	ret := _m.Called(ctx, userID, date)

	if len(ret) == 0 {
		panic("no return value specified for GetUserHistory")
	}

	var r0 []domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]domain.Booking, error)); ok {
		return rf(ctx, userID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []domain.Booking); ok {
		r0 = rf(ctx, userID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBooking provides a mock function with given fields: ctx, booking, roomNumber
func (_m *BookingUsecases) UpdateBooking(ctx context.Context, booking *domain.Booking, roomNumber uint) error {
	ret := _m.Called(ctx, booking, roomNumber)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Booking, uint) error); ok {
		r0 = rf(ctx, booking, roomNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBookingUsecases creates a new instance of BookingUsecases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookingUsecases(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookingUsecases {
	mock := &BookingUsecases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
