// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ApisitKhakmueang/BookingConferenceRoom/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ConfigPostgresRepo is an autogenerated mock type for the ConfigPostgresRepo type
type ConfigPostgresRepo struct {
	mock.Mock
}

// BulkUpsertHolidays provides a mock function with given fields: ctx, holidays
func (_m *ConfigPostgresRepo) BulkUpsertHolidays(ctx context.Context, holidays []domain.Holiday) error {
	ret := _m.Called(ctx, holidays)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsertHolidays")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Holiday) error); ok {
		r0 = rf(ctx, holidays)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetConfigDB provides a mock function with given fields: ctx
func (_m *ConfigPostgresRepo) GetConfigDB(ctx context.Context) (*domain.Config, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigDB")
	}

	var r0 *domain.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.Config, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.Config); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHolidayDB provides a mock function with given fields: ctx, date
func (_m *ConfigPostgresRepo) GetHolidayDB(ctx context.Context, date *domain.Date) ([]domain.Holiday, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetHolidayDB")
	}

	var r0 []domain.Holiday
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date) ([]domain.Holiday, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date) []domain.Holiday); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Holiday)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Date) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateConfigDB provides a mock function with given fields: ctx, config
func (_m *ConfigPostgresRepo) UpdateConfigDB(ctx context.Context, config *domain.Config) error {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConfigDB")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Config) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConfigPostgresRepo creates a new instance of ConfigPostgresRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigPostgresRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigPostgresRepo {
	mock := &ConfigPostgresRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
