// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/ApisitKhakmueang/BookingConferenceRoom/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ConfigGateWay is an autogenerated mock type for the ConfigGateWay type
type ConfigGateWay struct {
	mock.Mock
}

// FetchHolidays provides a mock function with given fields: date
func (_m *ConfigGateWay) FetchHolidays(date *domain.Date) ([]domain.Holiday, error) {
	ret := _m.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for FetchHolidays")
	}

	var r0 []domain.Holiday
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Date) ([]domain.Holiday, error)); ok {
		return rf(date)
	}
	if rf, ok := ret.Get(0).(func(*domain.Date) []domain.Holiday); ok {
		r0 = rf(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Holiday)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Date) error); ok {
		r1 = rf(date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewConfigGateWay creates a new instance of ConfigGateWay. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigGateWay(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigGateWay {
	mock := &ConfigGateWay{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
