// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ApisitKhakmueang/BookingConferenceRoom/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ConfigRedisRepo is an autogenerated mock type for the ConfigRedisRepo type
type ConfigRedisRepo struct {
	mock.Mock
}

// ClearCacheByPrefix provides a mock function with given fields: ctx, prefix
func (_m *ConfigRedisRepo) ClearCacheByPrefix(ctx context.Context, prefix string) error {
	ret := _m.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for ClearCacheByPrefix")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, prefix)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCache provides a mock function with given fields: ctx, prefix
func (_m *ConfigRedisRepo) DeleteCache(ctx context.Context, prefix string) {
	_m.Called(ctx, prefix)
}

// DeleteHolidayCache provides a mock function with given fields: ctx, date
func (_m *ConfigRedisRepo) DeleteHolidayCache(ctx context.Context, date *domain.Date) error {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for DeleteHolidayCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date) error); ok {
		r0 = rf(ctx, date)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindHolidaySynced provides a mock function with given fields: ctx, date
func (_m *ConfigRedisRepo) FindHolidaySynced(ctx context.Context, date *domain.Date) int64 {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for FindHolidaySynced")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date) int64); ok {
		r0 = rf(ctx, date)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// GetCache provides a mock function with given fields: ctx, cacheKey, dest
func (_m *ConfigRedisRepo) GetCache(ctx context.Context, cacheKey string, dest interface{}) error {
	ret := _m.Called(ctx, cacheKey, dest)

	if len(ret) == 0 {
		panic("no return value specified for GetCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, cacheKey, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetCache provides a mock function with given fields: ctx, cacheKey, data, expiration
func (_m *ConfigRedisRepo) SetCache(ctx context.Context, cacheKey string, data interface{}, expiration time.Duration) {
	_m.Called(ctx, cacheKey, data, expiration)
}

// SetHolidaySynced provides a mock function with given fields: ctx, date
func (_m *ConfigRedisRepo) SetHolidaySynced(ctx context.Context, date *domain.Date) error {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for SetHolidaySynced")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date) error); ok {
		r0 = rf(ctx, date)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConfigRedisRepo creates a new instance of ConfigRedisRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigRedisRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigRedisRepo {
	mock := &ConfigRedisRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
