// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ApisitKhakmueang/BookingConferenceRoom/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ConfigUsecase is an autogenerated mock type for the ConfigUsecase type
type ConfigUsecase struct {
	mock.Mock
}

// GetConfig provides a mock function with given fields: ctx
func (_m *ConfigUsecase) GetConfig(ctx context.Context) (*domain.Config, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 *domain.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.Config, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.Config); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHoliday provides a mock function with given fields: ctx, date
func (_m *ConfigUsecase) GetHoliday(ctx context.Context, date *domain.Date) ([]domain.Holiday, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetHoliday")
	}

	var r0 []domain.Holiday
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date) ([]domain.Holiday, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Date) []domain.Holiday); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Holiday)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Date) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateConfig provides a mock function with given fields: ctx, config
func (_m *ConfigUsecase) UpdateConfig(ctx context.Context, config *domain.Config) error {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Config) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConfigUsecase creates a new instance of ConfigUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigUsecase {
	mock := &ConfigUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
