// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RealtimePublisher is an autogenerated mock type for the RealtimePublisher type
type RealtimePublisher struct {
	mock.Mock
}

// PublishEvent provides a mock function with given fields: ctx, event, payload
func (_m *RealtimePublisher) PublishEvent(ctx context.Context, event string, payload interface{}) error {
	ret := _m.Called(ctx, event, payload)

	if len(ret) == 0 {
		panic("no return value specified for PublishEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, event, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRealtimePublisher creates a new instance of RealtimePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRealtimePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *RealtimePublisher {
	mock := &RealtimePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
