// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RedisCacheRepository is an autogenerated mock type for the RedisCacheRepository type
type RedisCacheRepository struct {
	mock.Mock
}

// ClearCacheByPrefix provides a mock function with given fields: ctx, prefix
func (_m *RedisCacheRepository) ClearCacheByPrefix(ctx context.Context, prefix string) error {
	ret := _m.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for ClearCacheByPrefix")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, prefix)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCache provides a mock function with given fields: ctx, prefix
func (_m *RedisCacheRepository) DeleteCache(ctx context.Context, prefix string) {
	_m.Called(ctx, prefix)
}

// GetCache provides a mock function with given fields: ctx, cacheKey, dest
func (_m *RedisCacheRepository) GetCache(ctx context.Context, cacheKey string, dest interface{}) error {
	ret := _m.Called(ctx, cacheKey, dest)

	if len(ret) == 0 {
		panic("no return value specified for GetCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, cacheKey, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetCache provides a mock function with given fields: ctx, cacheKey, data, expiration
func (_m *RedisCacheRepository) SetCache(ctx context.Context, cacheKey string, data interface{}, expiration time.Duration) {
	_m.Called(ctx, cacheKey, data, expiration)
}

// NewRedisCacheRepository creates a new instance of RedisCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisCacheRepository {
	mock := &RedisCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
