// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ApisitKhakmueang/BookingConferenceRoom/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// RoomPostgresRepo is an autogenerated mock type for the RoomPostgresRepo type
type RoomPostgresRepo struct {
	mock.Mock
}

// CreateRoomDB provides a mock function with given fields: ctx, room
func (_m *RoomPostgresRepo) CreateRoomDB(ctx context.Context, room *domain.Room) error {
	ret := _m.Called(ctx, room)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoomDB")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Room) error); ok {
		r0 = rf(ctx, room)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRoomDB provides a mock function with given fields: ctx, roomID
func (_m *RoomPostgresRepo) DeleteRoomDB(ctx context.Context, roomID uuid.UUID) error {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoomDB")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRoomByID_DB provides a mock function with given fields: ctx, roomID
func (_m *RoomPostgresRepo) GetRoomByID_DB(ctx context.Context, roomID uuid.UUID) (*domain.Room, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomByID_DB")
	}

	var r0 *domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Room, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Room); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoomDB provides a mock function with given fields: ctx
func (_m *RoomPostgresRepo) GetRoomDB(ctx context.Context) ([]domain.Room, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomDB")
	}

	var r0 []domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Room, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Room); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRoomDB provides a mock function with given fields: ctx, room
func (_m *RoomPostgresRepo) UpdateRoomDB(ctx context.Context, room *domain.Room) error {
	ret := _m.Called(ctx, room)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoomDB")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Room) error); ok {
		r0 = rf(ctx, room)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRoomPostgresRepo creates a new instance of RoomPostgresRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoomPostgresRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoomPostgresRepo {
	mock := &RoomPostgresRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
