// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ApisitKhakmueang/BookingConferenceRoom/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserPostgresRepo is an autogenerated mock type for the UserPostgresRepo type
type UserPostgresRepo struct {
	mock.Mock
}

// GetPaginatedUserBookingsDB provides a mock function with given fields: ctx, userID, q
func (_m *UserPostgresRepo) GetPaginatedUserBookingsDB(ctx context.Context, userID uuid.UUID, q *domain.BookingPaginationQuery) ([]domain.UserBookingHistoryRes, int64, error) {
	ret := _m.Called(ctx, userID, q)

	if len(ret) == 0 {
		panic("no return value specified for GetPaginatedUserBookingsDB")
	}

	var r0 []domain.UserBookingHistoryRes
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.BookingPaginationQuery) ([]domain.UserBookingHistoryRes, int64, error)); ok {
		return rf(ctx, userID, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.BookingPaginationQuery) []domain.UserBookingHistoryRes); ok {
		r0 = rf(ctx, userID, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserBookingHistoryRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *domain.BookingPaginationQuery) int64); ok {
		r1 = rf(ctx, userID, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, *domain.BookingPaginationQuery) error); ok {
		r2 = rf(ctx, userID, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPaginatedUsersDB provides a mock function with given fields: ctx, q
func (_m *UserPostgresRepo) GetPaginatedUsersDB(ctx context.Context, q *domain.UserPaginationQuery) ([]domain.User, int64, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetPaginatedUsersDB")
	}

	var r0 []domain.User
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserPaginationQuery) ([]domain.User, int64, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserPaginationQuery) []domain.User); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.UserPaginationQuery) int64); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *domain.UserPaginationQuery) error); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetUserOverviewDB provides a mock function with given fields: ctx, userID
func (_m *UserPostgresRepo) GetUserOverviewDB(ctx context.Context, userID uuid.UUID) (*domain.UserOverviewResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOverviewDB")
	}

	var r0 *domain.UserOverviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.UserOverviewResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.UserOverviewResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserOverviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserStatusDB provides a mock function with given fields: ctx, userID, newStatus
func (_m *UserPostgresRepo) UpdateUserStatusDB(ctx context.Context, userID uuid.UUID, newStatus string) error {
	ret := _m.Called(ctx, userID, newStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserStatusDB")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, newStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserPostgresRepo creates a new instance of UserPostgresRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserPostgresRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserPostgresRepo {
	mock := &UserPostgresRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
