// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ApisitKhakmueang/BookingConferenceRoom/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserUsecase is an autogenerated mock type for the UserUsecase type
type UserUsecase struct {
	mock.Mock
}

// GetPaginatedUserBookings provides a mock function with given fields: ctx, userID, q
func (_m *UserUsecase) GetPaginatedUserBookings(ctx context.Context, userID uuid.UUID, q *domain.BookingPaginationQuery) (*domain.PaginatedBookingResponse, error) {
	ret := _m.Called(ctx, userID, q)

	if len(ret) == 0 {
		panic("no return value specified for GetPaginatedUserBookings")
	}

	var r0 *domain.PaginatedBookingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.BookingPaginationQuery) (*domain.PaginatedBookingResponse, error)); ok {
		return rf(ctx, userID, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.BookingPaginationQuery) *domain.PaginatedBookingResponse); ok {
		r0 = rf(ctx, userID, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaginatedBookingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *domain.BookingPaginationQuery) error); ok {
		r1 = rf(ctx, userID, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaginatedUsers provides a mock function with given fields: ctx, q
func (_m *UserUsecase) GetPaginatedUsers(ctx context.Context, q *domain.UserPaginationQuery) (*domain.PaginatedUserResponse, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetPaginatedUsers")
	}

	var r0 *domain.PaginatedUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserPaginationQuery) (*domain.PaginatedUserResponse, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserPaginationQuery) *domain.PaginatedUserResponse); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaginatedUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.UserPaginationQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserOverview provides a mock function with given fields: ctx, userID
func (_m *UserUsecase) GetUserOverview(ctx context.Context, userID uuid.UUID) (*domain.UserOverviewResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOverview")
	}

	var r0 *domain.UserOverviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.UserOverviewResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.UserOverviewResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserOverviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserStatus provides a mock function with given fields: ctx, userID, newStatus
func (_m *UserUsecase) UpdateUserStatus(ctx context.Context, userID uuid.UUID, newStatus string) error {
	ret := _m.Called(ctx, userID, newStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, newStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserUsecase creates a new instance of UserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUsecase {
	mock := &UserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
