// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ApisitKhakmueang/BookingConferenceRoom/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// WorkerPostgresRepo is an autogenerated mock type for the WorkerPostgresRepo type
type WorkerPostgresRepo struct {
	mock.Mock
}

// GetBookingByID provides a mock function with given fields: ctx, id
func (_m *WorkerPostgresRepo) GetBookingByID(ctx context.Context, id uuid.UUID) (*domain.Booking, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingByID")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Booking, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Booking); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoomNumberDB provides a mock function with given fields: ctx, bookingID
func (_m *WorkerPostgresRepo) GetRoomNumberDB(ctx context.Context, bookingID uuid.UUID) (uint, error) {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomNumberDB")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uint, error)); ok {
		return rf(ctx, bookingID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) uint); ok {
		r0 = rf(ctx, bookingID)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBookingStatusDB provides a mock function with given fields: ctx, bookingID, status
func (_m *WorkerPostgresRepo) UpdateBookingStatusDB(ctx context.Context, bookingID uuid.UUID, status string) (*domain.Booking, error) {
	ret := _m.Called(ctx, bookingID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookingStatusDB")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*domain.Booking, error)); ok {
		return rf(ctx, bookingID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *domain.Booking); ok {
		r0 = rf(ctx, bookingID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, bookingID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWorkerPostgresRepo creates a new instance of WorkerPostgresRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkerPostgresRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkerPostgresRepo {
	mock := &WorkerPostgresRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
