// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ApisitKhakmueang/BookingConferenceRoom/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// WorkerUsecase is an autogenerated mock type for the WorkerUsecase type
type WorkerUsecase struct {
	mock.Mock
}

// GetBookingByID provides a mock function with given fields: ctx, id
func (_m *WorkerUsecase) GetBookingByID(ctx context.Context, id uuid.UUID) (*domain.Booking, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingByID")
	}

	var r0 *domain.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Booking, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Booking); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PublishRoomStatus provides a mock function with given fields: event, completedBooking
func (_m *WorkerUsecase) PublishRoomStatus(event string, completedBooking *domain.Booking) {
	_m.Called(event, completedBooking)
}

// PublishStatus provides a mock function with given fields: event, completedBooking
func (_m *WorkerUsecase) PublishStatus(event string, completedBooking *domain.Booking) {
	_m.Called(event, completedBooking)
}

// UpdateBookingEndStatus provides a mock function with given fields: ctx, bookingID
func (_m *WorkerUsecase) UpdateBookingEndStatus(ctx context.Context, bookingID uuid.UUID) error {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookingEndStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, bookingID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBookingNoshowStatus provides a mock function with given fields: ctx, bookingID
func (_m *WorkerUsecase) UpdateBookingNoshowStatus(ctx context.Context, bookingID uuid.UUID) error {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookingNoshowStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, bookingID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWorkerUsecase creates a new instance of WorkerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkerUsecase {
	mock := &WorkerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
